name: CI/CD NestJS AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      # Empaquetar el build en un ZIP para Elastic Beanstalk
      - name: Create deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "node_modules/*" "*.github/*"
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: backend_clean             # tu aplicación
          environment_name: Backenddev-env               # tu environment
          version_label: ${{ github.sha }}
          region: us-east-2                          # ajusta según tu región
          deployment_package: deploy.zip              # usamos el ZIP creado
          existing_bucket_name: elasticbeanstalk-us-east-2-070797854721        # bucket existente de EB
