name: CI/CD NestJS AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: backend_clean        # Cambiar por el nombre de tu app
          environment_name: backend_dev        # Cambiar por el nombre del environment
          version_label: ${{ github.sha }}
          region: us-east-1                      # Cambiar si tu región es distinta
          deployment_package: .                  # Carpeta raíz o ZIP con tu build
          existing_bucket_name: YOUR_S3_BUCKET  # Bucket de S3 que ya existe
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

