name: CI/CD NestJS AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: YOUR_APP_NAME
          environment_name: YOUR_ENV_NAME
          version_label: ${{ github.sha }}
          region: us-east-1 # Cambiar según tu región
          bucket_name: YOUR_S3_BUCKET # Elastic Beanstalk crea uno
          bucket_key: app-${{ github.sha }}.zip
          deployment_package: . # o carpeta que contenga dist y package.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
